### ISSUE TITLE
Build now FAILURE on the ssh-agent pipeline

### ISSUE THREAD

**Issue by DFranc-D** [LinkedInLearning/essential-jenkins-2468076#1]
## Issue Overview
When attempting to run the Build Now Pipeline ssh-agent it fails with the following:
Started by user [Franc](http://ec2-3-224-65-179.compute-1.amazonaws.com/user/franc)
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 4: Tool type "maven" does not have an install of "Maven-3.8.4" configured - did you mean "maven-3.8.4"? @ line 4, column 13.
         maven 'Maven-3.8.4'
               ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1107)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:677)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:689)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:513)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:335)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE

## Describe your environment
  I am using the same EC2 Ubuntu as my Jenkins Controller and an EC2 Ubuntu as Jenkins Agent node.

## Steps to Reproduce

1. Copy the current contents of the Jenkinsfile from https://github.com/LinkedInLearning/essential-jenkins-2468076/blob/6f23cc7a25d0af5a63e76f9da70109faea8d4538/Ch04/04_02-ssh-agent/Jenkinsfile
2. Paste it into the new created ssh-agent pipeline in your Jenkins Controller 
3. Click on Build now

## Expected Behavior

[Pipeline] End of Pipeline
Finished: SUCCESS
## Current Behavior

Finished: FAILURE # from the Jenkins Console
## Possible Solution

pipeline {
    agent { label 'linux' }
    tools {
      maven 'Maven-3.8.4'  #change the Uppercase M to lowercase m

**Comment by managedkaos** [comment]
In the lesson titled "Distribute builds with agents" at the time marked 4:34, the screen shows a maven configuration named 'Maven-3.8.4'.  The content also mentions to set up the same configuration if you are following along with the exercise files.

Please find the same on the link below: https://prnt.sc/t0iByFTk8cAR

Can you please confirm that you have in place a maven configuration that matches the configuration named in the video?  If indeed, yours has a lower case 'm', please update your configuration to match the lesson if you would like to use the exercise files without modification. 

Otherwise, please fork the exercise files and modify them as needed.

Thanks for viewing Jenkins Essential Training on LinkedIn Learning!
